name: terraform/apply
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read 

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: git checkoutt
        uses: actions/checkout@v5

      - name: configure aws credentials by web identity
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ secrets.AWS_REGION}}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: MySessionName

      - name: Setup Terraformm
        uses: hashicorp/setup-terraform@v3

      - name: Debug Variables
        run: env | grep TF_VAR

      - name: Terraform Init
        run: terraform init

      # - name: Terraform plan
      #   run: terraform plan -auto-approve